name: ci-cd

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: sbt test
        env:
          READ_GITHUB_PACKAGES_TOKEN: ${{ secrets.READ_GITHUB_PACKAGES_TOKEN }}

      - name: detailed test reporting
        uses: dorny/test-reporter@v1
        if: always()
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: Detailed Unit Tests Reporting
          path: "pipeline-interpreter/target/test-reports/*.xml"
          reporter: java-junit

      - name: basic test reporting
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "pipeline-interpreter/target/test-reports/*.xml"
          check_name: Basic Unit Tests Reporting
          comment_title: Tests Report
          time_unit: seconds
          job_summary: false